name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS }}
           # achievements
          plugin_achievements: yes
          plugin_achievements_threshold: B      # Display achievements with rank B or higher
          plugin_achievements_secrets: yes      # Display unlocked secrets achievements
          plugin_achievements_display: compact  # Use compact display
          plugin_achievements_limit: 0          # Display all unlocked achievements (no limit)
          # notable
          plugin_notable: yes
          plugin_notable_filter: stars:>100 # Only display repositories with 500 stars or more (syntax based on GitHub search query)
          plugin_notable_from: organization # Only display contributions within organization repositories
          plugin_notable_repositories: yes  # Display repositories name instead of only organization name
          plugin_notable_indepth: yes       # Gather additional informations about contributions
          # topics
          plugin_topics: yes
          plugin_topics_sort: stars    # Sort by most starred topics
          plugin_topics_mode: icons    # Display icons instead of labels
          plugin_topics_limit: 0       # Disable limitations
          # languages
          plugin_languages: yes